const products = [
    {
        '_id': '1',
        'name': 'Infinix Zero X',
        'image': '/products/phones/infinix zero x.jpg',
        'description': 'Get you game on with 8GB of RAM, 128GB ROM and the 2.0GHz Octa core Mediatek Heilo processor', 
        'brand': 'Infinix',
        'category': 'Electronics',
        'price': 120000, 
        'countInStock' : 10, 
        'rating' : 4.3, 
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'iphone XR 126GB 4GB',
        'image': '/products/phones/iphone xr blue.jpg',
        'description': '', 
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 130000, 
        'countInStock' : 7, 
        'rating' : 4.0, 
        'numReviews': 9,
    },
    {
        '_id': '3',
        'name': 'iphone 12 pro max',
        'image': '/products/phones/iphone-12-pro-max-silver.jpg',
        'description': 'Sleek design, ', 
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 156000, 
        'countInStock': 4, 
        'rating' : 4.1, 
        'numReviews': 8,
    },
    {
        '_id': '4',
        'name': 'Nokia 1 64GB 3GB',
        'image': '/products/phones/nokia 1.jpg',
        'description': 'solid and rigid, design to withstand the forces of nature', 
        'brand': 'Nokia',
        'category': 'Electronics',
        'price': 70000, 
        'countInStock' : 11, 
        'rating' : 3.9, 
        'numReviews': 5,
    },
    {
        '_id': '5',
        'name': 'Xiaomi Redmi 1',
        'image': '/products/phones/redmi 1.jpg',
        'description': '', 
        'brand': 'Xiaomi',
        'category': 'Electronics',
        'price': 63400, 
        'countInStock' : 17, 
        'rating' : 3.8, 
        'numReviews': 12,
    },
    {
        '_id': '6',
        'name': 'Samsung s21 ultra',
        'image': '/products/phones/samsung s21 ultra.jpg',
        'description': '', 
        'brand': 'Samsung',
        'category': 'Eletronics',
        'price': 230000, 
        'countInStock' : 19, 
        'rating' : 4.5, 
        'numReviews': 30,
    },
    {
        '_id': '7',
        'name': 'Tecno Phantom X',
        'image': '/products/phones/tecno phantom x.jpg',
        'description': 'Experience more with tecno', 
        'brand': 'Tecno',
        'category': 'Electronics',
        'price': 150000, 
        'countInStock' : 30, 
        'rating' : 4.1, 
        'numReviews': 9,
    },
    {
        '_id': '8',
        'name': 'Vivo Y19',
        'image': '/products/phones/vivo y19.jpg',
        'description': '', 
        'brand': 'VIVO',
        'category': 'Electronics',
        'price': 45000, 
        'countInStock' : 4, 
        'rating' : 3.5, 
        'numReviews': 9,
    },
    {
        '_id': '9',
        'name': 'Microsoft Surface Pro',
        'image': '/products/Laptops and computers/MS surface.jpg',
        'description': '', 
        'brand': 'Microsoft',
        'category': 'Electronics',
        'price': 169000, 
        'countInStock' : 11, 
        'rating' : 3.9, 
        'numReviews': 7,
    },
    {
        '_id': '10',
        'name': 'HP 15 500GB 16GB',
        'image': '/products/Laptops and Computers/hp laptop 1.png',
        'description': '', 
        'brand': 'HP',
        'category': 'Electronics',
        'price': 175000, 
        'countInStock' : 17, 
        'rating' : 4.4, 
        'numReviews': 23,
    },
    {
        '_id': '11',
        'name': 'Dell Alienware',
        'image': '/products/Laptops and Computers/Laptop 2.jpg',
        'description': 'The Gaming Beast himself', 
        'brand': 'Dell',
        'category': 'Electronics',
        'price': 540000, 
        'countInStock' : 6, 
        'rating' : 5.0, 
        'numReviews': 19,
    },
    {
        '_id': '12',
        'name': 'Acer Predator ',
        'image': '/products/Laptops and Computers/Laptop 3.jpg',
        'description': 'Gaming', 
        'brand': 'Acer',
        'category': 'Electronics',
        'price': 520000, 
        'countInStock' : 5, 
        'rating' : 4.9, 
        'numReviews': 11,
    },



]


export default products